name: ht_preferences_client
description: Abstract client for managing user preferences for the headlines toolkit app.
repository: https://github.com/headlines-toolkit/ht-preferences-client
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  equatable: ^2.0.7
  ht_categories_client:
    git:
      url: https://github.com/headlines-toolkit/ht-categories-client.git
  ht_countries_client:
    git:
      url: https://github.com/headlines-toolkit/ht-countries-client.git
  ht_headlines_client:
    git:
      url: https://github.com/headlines-toolkit/ht-headlines-client.git
  ht_sources_client:
    git:
      url: https://github.com/headlines-toolkit/ht-sources-client.git

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^7.0.0
