name: ht_preferences_client
description: Client for managing user preferences for the headlines toolkit app.
publish_to: none
repository: https://github.com/headlines-toolkit/ht-preferences-client

environment:
  sdk: ^3.5.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^7.0.0
